- app/views/applications/show.html.erb
-replaced link_to with button_to
> tweaked button

- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pets_controller.rb
- app/views/pets/edit.html.erb
- app/views/pets/index.html.erb
- app/views/pets/new.html.erb
- app/views/pets/show.html.erb
Added index, show, new, create, edit, update and destroy methods. Created associated views and added initial HTML to these.
> Pets controller

- app/assets/stylesheets/components/_card.scss
- app/views/pets/index.html.erb
Worked on the index view in pets pages - adding a grid and CSS to each iteration of card.
> Styled card components

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_pets_show.scss
- app/views/pets/show.html.erb
- db/seeds.rb
Created the layout and added CSS to the pets show page. Will still need to add in a photo carousel, description and lister's profile details later once we are able to pull this through.
> Pets show page

- Gemfile
- Gemfile.lock
- app/controllers/pets_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/models/pet.rb
- app/views/layouts/application.html.erb
- app/views/pets/show.html.erb
- config/initializers/geocoder.rb
- db/migrate/20220908091217_add_coordinates_to_pets.rb
- db/schema.rb
- db/seeds.rb
-mapbox added to pets shpw 
-will work whenever the pet's location is valid for geocoding
> Maps on pets show

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Styled the home page search bar and amended the nav bar to show the title unless it's on the home page
> Home page search bar styling

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
Customized footer by adding some initial styling. Edited logo in footer and nav bar to link to the home page correctly.
> Customize footer

- app/controllers/applications_controller.rb
- app/models/application.rb
- app/views/layouts/application.html.erb
- app/views/pets/show.html.erb
- db/migrate/20220912093718_add_default_value_to_pets.rb
- db/migrate/20220912113527_add_column_to_application.rb
- db/schema.rb
- owner can now accept or deny applications from the pets show 
- applications schema updated to included a validated column for this logic to work 
- owners show now varies by applications validated or not validated , and then application approved or not approved
> owner can now accept or deny user applications for their pet

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_pets_show.scss
- app/views/pets/show.html.erb
- db/seeds.rb
Edited the flexbox layout, added a favourite button, added pet lister's avatar and more details for the pet.
> Style show page

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
Made footer fixed at the bottom and no longer sticky. Added our Github profile links to the footer.
> Edit footer

- app/views/pets/show.html.erb
- app/views/users/show.html.erb
- pets show logic added for adopters 
- adopters can now see if their application has been accepted, denied, or is pending
> Application update for adopters

- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pets/index.html.erb
- db/schema.rb
Initial styling of search filters on pets index page - centered them, added placeholders, border radius, box shadow, padding and colors
> Style search filter

- app/channels/application_channel.rb
- app/controllers/applications_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/application_subscription_controller.js
- app/javascript/controllers/index.js
- app/views/applications/show.html.erb
- app/views/messages/_message.html.erb
- package.json
- test/channels/application_channel_test.rb
- yarn.lock
- added core functionality of messaging between users through applications show
> Messages between users

- app/views/applications/show.html.erb
- app/views/pets/index.html.erb
- app/views/users/show.html.erb
-species.downcase added 
- approved show if added
> downcase and applications approved only message show

- app/views/applications/index.html.erb
- app/views/applications/show.html.erb
- app/views/pets/show.html.erb
- app/views/shared/_navbar.html.erb
-links added to messages (application show chatbox) for two user types adopter, owner
-user profile links still needed
> links added to applications show chatbox

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_pets_show.scss
- app/views/pets/show.html.erb
Subtly edited layout in cards and changed the colours of the buttons
> Edit show page

- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
-navbar fix
-more chatbox links added
> navbar fix

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_favourites_show.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/favourites/index.html.erb
Added flexbox to each card and positioned the name and description relative to the whole card, added some styling
> Completed initial styling of cards

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
- Added Browse Pets to nav bar and moved deleted Messages from nav bar until we have an appropriate page to redirect to
- Added some styling to the nav bar links on hover
> Change navbar links

- app/views/pets/show.html.erb
-indentation amended for pets show
-divs cleaned up
> style and indentation amended

- app/views/applications/show.html.erb
Added edit application button, added pet photo and allowed users to view all inputs related to their application. Small styling tweaks to buttons - add more styling in CSS file later.
> Edit applications show

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_pets_show.scss
> Edit fonts

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Amended home page buttons colors and sizes
> Edit header search bar

- app/assets/stylesheets/pages/_favourites_show.scss
- app/views/favourites/index.html.erb
Deleted go to favourite and delete favourite buttons. Instead added a delete icon and linked the whole card to the pets show page. Still need to add extra styling to card text.
> Change favourite show buttons

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_pets_show.scss
- app/views/pets/show.html.erb
Updated button colours for edit and delete buttons and amended layout. Amended pet image size.
> Edited style of pets show page
